version: '3.3'

services:
  restapi.postgres:
    container_name: elc
    image: postgres:13
    volumes:
      - postgres:/var/lib/postgres
    restart: always
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    env_file:
      - ./.env
    labels:
      com.startupteam.description: "postgres container for elc"

volumes:
  postgres: {}
